app/models/angel.rb, app/models/user.rb, db/migrate/20201102143348_create_angels.rb, db/migrate/20201102144310_add_name_to_users.rb, db/schema.rb, test/models/angel_test.rb
angel model created with dependance :destroy from user
=> models and associations created

app/assets/config/colors.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/config/_fonts.scss
Colors and fonts are defined in stylesheet.
=> added colors and fonts

app/assets/stylesheets/application.scss, app/views/pages/fakecall.html.erb, app/views/pages/incoming.html.erb, app/views/pages/profile.html.erb, app/views/pages/tutorial.html.erb
added linking buttons to connect incoming-call, fakecall, profile, tutorial
=> connecting buttons

test_call_whatsapp.rb
Created a file test_call_whatsapp in which I implemented the logic to interact with the twilio API and perform calls to multiple users, when one answers it rereoutes to the user of the App that initiated the calls through the call button.
Implemented also the Twilio API logic for the Whatsapp sending location messages
=> tested and implemented twilio integration with test user

app/controllers/pages_controller.rb, config/routes.rb
twilio methods are now in the private fo pages controller
map route and map method is there
=> implemented twilio methods in controllers

test_call_whatsapp.rb
Changed some minor refactoring
=> refactored some things in the code

.gitignore, app/controllers/pages_controller.rb, db/seeds.rb, lib/twilio_methods.rb, test_call_whatsapp.rb
seeds for everyone of us name@gmail psw 123456 with our real phone number and we are each other angels
=> Seeds first draft

.gitignore, app/controllers/pages_controller.rb, config/environments/development.rb, db/seeds.rb, lib/twilio_methods.rb, test_call_whatsapp.rb
Added config to use ngrok to broadcast to mobile
=> Pwa close enough

app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_text.scss, app/views/pages/incoming.html.erb
created name(dad) and mobile 
-> is centered
created _text.scss
created green small buttons for location and 2nd call
=> Add name and mobile

app/assets/stylesheets/components/_navbar.scss, app/javascript/components/send_location.js, app/javascript/packs/application.js, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb
changed location to components and andded if statement to execute the addEventListener only when geoLoc id exists
=> Location js file in components

app/assets/stylesheets/components/_navbar.scss, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb
Created navbar sticky to bottom for mobile use only
=> navbar mobile finished

app/views/layouts/application.html.erb, app/views/pages/map.html.erb, app/views/pages/profile.html.erb, app/views/pages/tutorial.html.erb
ups i might have pushed to master..
=> flshes out, navbar only where needed

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/components/_text.scss, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/profile.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20201104141812_create_active_storage_tables.active_storage.rb, db/schema.rb
=> Cloudinary

app/views/pages/incoming.html.erb
It works.. let's see if it does on heroku!
=> Recording working no autoplay

app/javascript/ember-cli-build.js, app/javascript/packs/application.js, package.json, yarn.lock
=> test-pwa-3-installed-ember-installed

app/assets/stylesheets/components/_navbar.scss, app/controllers/pages_controller.rb, app/views/pages/map.html.erb, app/views/pages/profile.html.erb, app/views/shared/_navbar.html.erb
Fixed navbar heigh 
Improved style of map
=> try for maps and fixed navbar

config/webpack/environment.js
added this to enviroment.js 
environment.loaders.delete('nodeModules')
=> test-4 pwa

app/javascript/components/timer.js, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/pages/fakecall.html.erb
if statement for countdown and map centered to  parma
=> countdown works and map starts from parma

app/assets/stylesheets/components/_text.scss, app/views/pages/fakecall.html.erb, app/views/pages/incoming.html.erb
=> calls ready only js missing

app/javascript/components/timer.js, app/javascript/packs/application.js
=> countdown and up is working

app/javascript/components/audio_commands.js, app/javascript/components/timer.js, app/javascript/packs/application.js, app/views/pages/incoming.html.erb, app/views/pages/welcome.html.erb
Connected audio and fixed counter
=> audio connected

app/assets/stylesheets/pages/_index.scss, app/javascript/packs/application.js, app/views/pages/fakecall.html.erb
=> Fixing import

app/views/pages/fakecall.html.erb
=> removed i tag from call angels

app/assets/stylesheets/config/_colors.scss
changed background color to show on reflector
=> changed background color

app/assets/stylesheets/pages/_tutorial.scss, app/views/pages/tutorial.html.erb
modified tutorial
added learn more
=> fixed tutorial

app/assets/stylesheets/components/_btn.scss, app/views/pages/profile.html.erb
log out button in profile
alert
=> log out and alert works

app/javascript/components/audio_commands.js, app/javascript/packs/application.js, app/views/pages/fakecall.html.erb, app/views/shared/_navbar.html.erb
=> audio restarts

app/controllers/angels_controller.rb, app/views/angels/edit.html.erb, app/views/pages/profile.html.erb, config/routes.rb
- added routes edit, update, destroy 
- added methods in angels_controller
- added buttons in profile page
=> Added routes + edit and delete buttons for angels

lib/twilio_methods.rb
Changed env variables and API numbers in the twilio methods module
=> twilio credentials resetted

app/javascript/components/audio_commands.js, app/javascript/packs/application.js
=> second audio implemented

app/views/pages/map.html.erb, app/views/pages/profile.html.erb, app/views/pages/welcome.html.erb
Changed WithU in kursive in map, welcome page
Changed in alert (logout) we do not recommend.. to WithU does not recommend...
=> WithU is kursive

db/seeds.rb
modified coordinates in seeds for Milano
=> coordinates in milano now

app/assets/stylesheets/components/_btn.scss, app/assets/stylesheets/components/_profstyle.scss, app/assets/stylesheets/components/_text.scss, app/views/pages/profile.html.erb
added headers in profil
centered logout
=> modified profile

app/views/pages/map.html.erb
=> fixed height

app/javascript/components/script.js, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/pages/fakecall.html.erb
added metatags for facebook in the head
added script to fakecall view.
=> Script fake phone

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_new.scss, app/views/devise/sessions/new.html.erb
- modified style for sign-in form (form position + added color purple for the form header)
=> sign-in-form-design

app/javascript/components/script.js, app/javascript/packs/application.js
Implemented logic for playing the second script according to the status of the second call button
=> Second call script

app/javascript/components/script.js
=> script for second call works

app/assets/stylesheets/pages/_new.scss, app/views/devise/registrations/new.html.erb
=> DRAFT Modified sign-up form

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_new.scss, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> basic styling for edit user, sign up, sign in

app/assets/config/colors.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss
=> changed width based on media and reset gray profile to original

app/controllers/angels_controller.rb, app/controllers/application_controller.rb, app/controllers/maps_controller.rb, app/controllers/pages_controller.rb, app/models/angel.rb, app/models/user.rb, app/views/angels/edit.html.erb, app/views/angels/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/pages/profile.html.erb, db/migrate/20201123140819_add_prefix_to_angels.rb, db/migrate/20201123141304_add_prefix_to_users.rb, db/schema.rb, lib/twilio_methods.rb
added prefix box, unable to add it to number yet
=> Prefix - TO DO: fix send sms including prefixes

app/javascript/components/script.js, app/javascript/packs/application.js
Implemented audios
Timing is pretty good, the voice is good enough :)
We will use a real actor at some point for some good stuff
=> Audios and script changed into italian
